### ISSUE TITLE
Support for UWP?

### ISSUE THREAD

**Issue by corliss** [michaeled/FormsPopup#10]
Hi, are you planning to support UWP? If so, how soon?
Thanks.

**Comment by michaeled** [comment]
I'll be opening this back up soon. I'm going to use it as material for a [XenForms](http://www.xenforms.com) demo. I'll be addressing the open issues with iPhone & Android, first. I'll move to UWP, after.

**Comment by michaeled** [comment]
I won't be targeting UWP, i'll take any pull requests with UWP support.
