### ISSUE TITLE
Plugin blocks .forms entry ?

### ISSUE THREAD

**Issue by JustMeDaFaq** [michaeled/FormsPopup#12]
Hi, 
im actually using an entry on my contentpage, when using:
new PopupPageInitializer(this) {Handler.popup};

the entry element gets unusable.
Is there anything i can do bout it? Im using latest xamarin.forms.

Entry reference: https://developer.xamarin.com/guides/xamarin-forms/user-interface/text/entry/

**Comment by JustMeDaFaq** [comment]
Same for the searchbar, if the contentpage which gets initialized with:
PopupPageInitializer(this) {Handler.popup};

Searchbar doesnt work anymore on the page.

**Comment by michaeled** [comment]
Can you provide me an example if this is still an issue?

**Comment by michaeled** [comment]
I believe this has been resolved.
