### ISSUE TITLE
Animating popup closing

### ISSUE THREAD

**Issue by robmpreston** [michaeled/FormsPopup#3]
Hey,

I have a popup that slides up from the bottom of the screen. The animation works fine for when it opens, but im not sure how to get it to work when it closes? 

This is the code I have:

```
        closeButton.Clicked += async (s,e) => {
            double original;

            await _popup.HideAsync(async p => 
                {
                    await Task.WhenAll
                    (
                        p.SectionContainer.TranslateTo(0, 250, 250)
                    );
                });
        };
```

But when I click to close it just instantly closes without sliding offscreen first.

**Comment by michaeled** [comment]
I've fixed and commited the change. Go ahead and get latest.

**Comment by robmpreston** [comment]
working perfectly, thanks. thought i was doing something wrong :)
