### ISSUE TITLE
Setting Top/Left/Right/BottomBorderColor doesnt function

### ISSUE THREAD

**Issue by robmpreston** [michaeled/FormsPopup#4]
Doesnt seem to be working, set all 4 to black, no borders anywhere.

**Comment by robmpreston** [comment]
Also noticed that when I put the header inside of a Grid, it seems to be messing up the content in the Body. i tried using a stacklayout and a grid in the body after using a grid in the header and the content is off or not displaying.

**Comment by michaeled** [comment]
I was able to reproduce those. I'll get a fix out this evening.

**Comment by michaeled** [comment]
It's been resolved.
You'll need to set each individual border color, even if they're all the same.

I added ComplexLayoutExample.xaml that has what I thought would reproduce your issue. If you still have it, let me know. I'd like you to post the code.

**Comment by robmpreston** [comment]
Cool ill check it out tonight

**Comment by robmpreston** [comment]
Working great now man, thanks for the quick fixes.
