### ISSUE TITLE
Is it possible to make the popup window transparent?

### ISSUE THREAD

**Issue by robmpreston** [michaeled/FormsPopup#5]
Just curious if I can have a slide up and have the background see through to the page behind it?

**Comment by michaeled** [comment]
At the moment, I don't think you'll get the result you probably want.
You can change the opacity property of the popup control, but it will also make all the popup's child controls transparent. 

A solutions escaping me, so let me think on this.

**Comment by robmpreston** [comment]
Okay let me know if you come up with anything :)

**Comment by robmpreston** [comment]
Did you ever have any thoughts on this? Would be great to be able to set the Opacity to .5 on the popup, but still set the opacity of controls on the popup to 1

**Comment by michaeled** [comment]
I'll have time to look into it this Friday. I'll let you know.

**Comment by michaeled** [comment]
Not at this moment.
