### ISSUE TITLE
Popop has zero width in iOS9

### ISSUE THREAD

**Issue by johandep** [michaeled/FormsPopup#9]
Hi,
You've created a great component for use in XF. I've tested in our project and I noticed that the popup in iOS 9 always has a width of 0 and is placed in the top left corner the first time when you open the popup. If you rotate the screen and show the popup again, it's placed correctly. It seems that the width is calculated wrong somewhere.
Can you have a look at this? I've tested this with iOS9 simulator and XF 1.5.0.6446.
Best regards,
Johan.

**Comment by michaeled** [comment]
I can look at it this weekend. Thanks for reporting it!

**Comment by johandep** [comment]
Great! Thank you.

Best regards,

Johan.

**Comment by robmpreston** [comment]
any word on any of these updates / fixes? has been sitting idle for a long time now. i plan to use it in a production app but cant as is.

**Comment by michaeled** [comment]
I don't own a mac, so I offload all the iOS work to another dev. He's been traveling quite a bit, so I'm going to bite the bullet and purchase a mac.

**Comment by robmpreston** [comment]
Guessing this is on hold for now? :)

**Comment by michaeled** [comment]
For the time being. I'm heads down on a UI builder for Xamarin Forms. I'll pick this back up after. I'll accept pull request, though. :)

**Comment by mxstudios** [comment]
Michael,

Definitely interested in seeing the UI builder when ready. That was a project I considered tackling. I'll look at your code on this popup and see if I can figure out the ios9 issue. Need this for a project and like the way you did it.

Greg

**Comment by michaeled** [comment]
I've released a video of the ui inspector, if you want to take a look at it.
http://www.xenforms.com
